# test config mushra page, no waveform, 3 conditions,  looping, anchor35, anchor 70


testname: Singing Voice Synthesis - Welcome
testId: welcome_page
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
  - type: generic
    id: all
    name: Welcome!
    content: <p style="width:70%; margin:auto;">
             <br><br><br><br><br>
             <b>This survey is now closed.</b><br>
             Thank you for your participation!
             <br><br><br><br><br>
             </script>

 
             

