# test config mushra page, no waveform, 3 conditions,  looping, anchor35, anchor 70


testname: Singing Voice Synthesis - Evaluation
testId: mushra_customquestionaire
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:        
  - type: generic
    id: all
    name: Welcome
    content: Round 1
  - type: volume
    id: vol
    name: Volume Settings
    content: Please adjust the volume. You will not be able to adjusted it after this page.
    stimulus: configs/resources/audio/results_wav/f1_a/audio/original.wav
    defaultVolume: 0.5

  - type: generic
    id: all
    name: All listening tests
    content: This page describes what is to be done in the following test. Four stimuli are presented
  -
    - random
    
    - type: mushra
      id: f1_a
      name: Mono Trial
      content: Please rate the quality of all stimuli.
      showWaveform: true
      enableLooping: true 
      randomize: true 
      reference: configs/resources/audio/results_wav/f1_a/audio/original.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/results_wav/f1_a/audio/harmonic.wav
          C2: configs/resources/audio/results_wav/f1_a/audio/synthesis_estimated.wav
          C3: configs/resources/audio/results_wav/f1_a/audio/synthesized_f1_a.wav
          C4: configs/resources/audio/results_wav/f1_a/audio/anchor35.wav


    - type: mushra
      id: f1_i
      name: Mono Trial
      content: Please rate the quality of all stimuli.
      showWaveform: true
      enableLooping: true
      randomize: true
      reference: configs/resources/audio/results_wav/f1_i/audio/original.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/results_wav/f1_i/audio/harmonic.wav
          C2: configs/resources/audio/results_wav/f1_i/audio/synthesis_estimated.wav
          C3: configs/resources/audio/results_wav/f1_i/audio/synthesized_f1_i.wav
          C4: configs/resources/audio/results_wav/f1_i/audio/anchor35.wav

  - type: finish
    name: Thank you
    content: Thank you for attending
    popupcontent: Your results were sent. Goodbye and have a nice day
    showResults: true
    writeResults: true
    questionnaire:
        - type: text
          label: eMail
          name: email
        - type: number
          label: Age
          name: age
          min: 0
          max: 100
          default: 30
        - type: likert
          name: gender
          label: Gender
          response:
            - value: female
              label: Female
            - value: male
              label: Male
            - value: other
              label: Other
