# test config mushra page, no waveform, 3 conditions,  looping, anchor35, anchor 70


testname: Singing Voice Synthesis - Evaluation
testId: quality_ab_experiment
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:


  - type: quality_ab
    id: f1_a
    name: Mono Trial
    content: Please rate the quality of all stimuli.
    showWaveform: true
    enableLooping: true 
    randomize: true 
    reference: configs/resources/audio/results_wav/f1_a/audio/original.wav
    stimulus:  configs/resources/audio/results_wav/f1_a/audio/synthesized_f1_a.wav
    reversed_order: true
    qualityItems:
        - Item: Nasalality
          Label: Nasalality
          Description: Which of the stimuli sounds more nasalized?
        - Item: Vibrato
          Label: Vibrato
          Description: Which of the stimuli contains more vibrato?
        - Item: Breathiness
          Label: Breathiness
          Description: Which of the stimuli is more breathy?
        - Item: Roughness
          Label: Roughness
          Description: Which is the stimuli is more rough?
        - Item: Naturalness
          Label: Naturalness
          Description: Which is the stimuli sounds more natural?
        - Item: Brilliance
          Label: Brilliance
          Description: Which is the stimuli contains more high frequencies?

  - type: quality_ab
    id: f4_o
    name: Mono Trial 2
    content: Please rate the quality of all stimuli.
    showWaveform: true
    enableLooping: true 
    randomize: true 
    reference: configs/resources/audio/results_wav/f4_o/audio/original.wav
    stimulus:  configs/resources/audio/results_wav/f4_o/audio/synthesized_f4_o.wav
    reversed_order: false
    qualityItems:
        - Item: Nasalality
          Label: Nasalality
          Description: Which of the stimuli sounds more nasalized?
        - Item: Vibrato
          Label: Vibrato
          Description: Which of the stimuli contains more vibrato?
        - Item: Breathiness
          Label: Breathiness
          Description: Which of the stimuli is more breathy?
        - Item: Roughness
          Label: Roughness
          Description: Which is the stimuli is more rough?
        - Item: Naturalness
          Label: Naturalness
          Description: Which is the stimuli sounds more natural?
        - Item: Brilliance
          Label: Brilliance
          Description: Which is the stimuli contains more high frequencies?
        
  - type: finish
    name: Thank you
    content: Thank you for attending
    popupcontent: Your results were sent. Goodbye and have a nice day
    showResults: true
    writeResults: true
    questionnaire:
        - type: text
          label: eMail
          name: email
          optional: true
        - type: number
          label: Age
          name: age
          min: 0
          max: 100
          default: 30
        - type: likert
          name: gender
          label: Gender
          optional: true
          response:
            - value: female
              label: Female
            - value: male
              label: Male
            - value: other
              label: Other